# Generated by Django 4.1.2 on 2022-10-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0005_alter_entry_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(related_name='en', to='kj.author'),
        ),
    ]
