# Generated by Django 4.1.2 on 2022-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0010_publication_remove_article_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
