# Generated by Django 4.1.2 on 2022-10-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0011_student1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
