# Generated by Django 4.1.2 on 2022-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0013_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
