# Generated by Django 4.1.2 on 2022-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0015_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
