# Generated by Django 4.1.2 on 2022-10-31 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0016_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kj.author'),
            preserve_default=False,
        ),
    ]
