# Generated by Django 4.1.2 on 2022-10-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0017_author_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kj.author'),
        ),
    ]
