# Generated by Django 4.1.2 on 2022-10-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0018_alter_author_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
