# Generated by Django 4.1.2 on 2022-10-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0019_remove_entry_authors_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
