# Generated by Django 4.1.2 on 2022-10-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0021_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
