# Generated by Django 4.1.2 on 2022-11-04 09:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0023_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('author', django.db.models.manager.Manager()),
            ],
        ),
    ]
