# Generated by Django 4.1.2 on 2022-11-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0024_alter_author_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
            ],
        ),
    ]
