# Generated by Django 4.1.2 on 2022-11-09 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kj', '0025_alter_author_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('ob', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='au',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s', to='kj.author'),
        ),
    ]
